### ISSUE TITLE
Installed, Can see in Cockpit but doesn't work

### ISSUE THREAD

**Issue by davedoc1984** [sairuk/cockpit-xboxmanager#1]
I have got the Xbox Manager installed, can see it in the Cockpit Menu, have put my Xbox IP Address in the Config tab and clicked Update but the Manager doesn't seem to connect to my Xbox.

![image](https://user-images.githubusercontent.com/97349996/170888254-79ed1128-6348-479b-9dab-4c567334d20c.png)

![image](https://user-images.githubusercontent.com/97349996/170888292-99a5f895-5fa9-4b05-91e4-bb4fca6c3f4c.png)

**Comment by sairuk** [comment]
does the mount directory exist? it needs to exist and be rw for the xbox connection to be completed

**Comment by davedoc1984** [comment]
Yes if you mean on the Xbox.

F Drive and games.

**Comment by sairuk** [comment]
no i refer to the mount directory listed in the options screen

**Comment by davedoc1984** [comment]
![image](https://user-images.githubusercontent.com/97349996/170890090-2901836f-00c9-4234-ab84-37da58b0b285.png)
It would appear not. How do I go about creating that?

**Comment by sairuk** [comment]
make a directory anywhere on your file system that your retronas user has read/write access to then configure that path in the options screen

something like `mkdir retronas_data_dir/mount/xbox` changing `retronas_data_dir` to whatever makes sense for your setup

or put it in your retronas users home directory whatever that user is

**Comment by davedoc1984** [comment]
I have done this, created a folder, put the path to it in the Mount section and clicked Update. Nothing has happened.

**Comment by sairuk** [comment]
alright, thanks for the feedback. that should be all you need.

providing these are configured correctly and you've confirmed the settings
- xbox ip, user, pass, games drive and dir
- mount direction r/w
- local xbox directory r/w

you could run the xboxmanager script as the retronas user from the terminal for potentially more output to see where its crashing. Cockpit is a pain in picking up output atm.

these may not be correct I can't test them right now
change mount dir/retronas_user to whatever your system uses
```
su - <retronas user>
/opt/xboxmanager/scripts/xboxmanager.sh -m status -i 192.168.0.48
/opt/xboxmanager/scripts/xboxmanager.sh -m mount -i 192.168.0.48 -u xbox -p xbox -l <mount dir>
/opt/xboxmanager/scripts/xboxmanager.sh -m status -i 192.168.0.48
/opt/xboxmanager/scripts/xboxmanager.sh -m list-installed -l <mount dir> -f F -t games
/opt/xboxmanager/scripts/xboxmanager.sh -m umount
```

 if its still not working and you've confirmed the settings are OK, i'll have to get setup to test it here again at some point.

**Comment by davedoc1984** [comment]
Something is clearly not right here. After doing SU

Then trying the 1st command in your list.. I get this:

![image](https://user-images.githubusercontent.com/97349996/170890974-2cfbeb5f-263b-4cfc-a233-6a89b012e22f.png)

**Comment by sairuk** [comment]
yeh `-h` should be `-i` i've fixed that in my post, you are also still running as `root` is your normal retronas user `root`?

**Comment by davedoc1984** [comment]
Yep my normal retronas user is Root.

pi is also used for things like the MiSTer and PS2 etc?

**Comment by sairuk** [comment]
ok so you should be running the xboxmanager script as the `pi` user, it will run from cockpit unprivileged so if you start to do operations as `root` on the cli with this your going run into silent permissions errors when using it from cockpit later on.

when i say retronas_user I mean the unprivileged `pi` user

this is experimental software, running it as `root` has the potential to nuke your entire system until i'm satisfied i've squashed potential bugs in the uninstall.

**Comment by davedoc1984** [comment]
ok... now its telling me it can't find extract-xiso can't help you bro when I have run the commands to install this.

**Comment by sairuk** [comment]
ah yep, very good thanks.

i assume this command doesn't come back with anything?

```
which extract-xiso
```

**Comment by davedoc1984** [comment]
Indeed that comes back with nothing.

**Comment by sairuk** [comment]
thanks you've helped me identify the problem, I will look at putting in a fix when I get to my desk a little later on. I will update here when done

**Comment by sairuk** [comment]
one more thing what does this look like? 

```
ls /usr/local/bin/extract-xiso
```

I am looking over the retronas installer and it should have built extract-xiso into this directory in your path

**Comment by davedoc1984** [comment]
![image](https://user-images.githubusercontent.com/97349996/170891658-83cedc6c-f0cd-4cd1-9cab-d75903d8fecf.png)

**Comment by sairuk** [comment]
ok extract-xiso from retronas did not install properly, that is where the problem is

**Comment by davedoc1984** [comment]
Working now :)

**Comment by davedoc1984** [comment]
Went into experimental (within the Retronas Install / Config menu and ran the XboxManager (experimental) option which has sorted this out.

**Comment by sairuk** [comment]
this issue will help drive some doco around this project, so good work for both of us

thanks for letting me know what you did to fix it
